/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package daic

import java.text.NumberFormat

class App {
    private static final Locale locale = new Locale('da', 'dk')
    private static final NumberFormat formatter = initFormatter()

    static void main(String[] args) {
        if (args == null || args.size() < 3) {
            println 'Error running program. Printing help...'
            println ''
            println 'This program helps calculating a rough baseline for a yearly income, based on hourly wage, and the '
            println 'number of hours work per day. This is takes into acount the number of days that are common workdays'
            println 'each week (Monday - Friday)'
            println ''
            println "Needs three ordered arguments: <YEAR> <WAGE> <HOURS>"
            println ' - YEAR: The year to calculate the income for'
            println ' - WAGE: Your hourly wage'
            println ' - HOURS: The number of hours spend working each day (can be a decimal)'
            System.exit(-1)
        }

        def year = Integer.valueOf(args[0])

        def calculator = new IncomeCalculator(
            year,
            Double.valueOf(args[1]),
            Double.valueOf(args[2])
        )

        println "Indkomst for ${year}"
        println "Sum: ${printMoney(calculator.annualSum())}"
        println "Efter ATP-bidrag: ${printMoney(calculator.annualSumAfterATP())}"
        println "Efter AM-bidrag: ${printMoney(calculator.annualSumAfterAM())}"
    }

    private static printMoney(double amount) {
        "${formatter.format(amount)} kr."
    }

    private static NumberFormat initFormatter() {
        def f = NumberFormat.getInstance(locale)
        f.setMinimumFractionDigits(2)
        f.setMaximumFractionDigits(2)
        return f
    }
}
